projects:
  atlas:
    schemaPath: amplify/backend/api/atlas/build/schema.graphql
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
extensions:
  amplify:
    version: 3
