//
//  HistoryInteractor.swift
//  Atlas
//
//  Created by Parvin Sital on 03/08/2020.
//  Copyright (c) 2020 Parvin Sital. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryLogic {
    func viewDidFinishLoading()
}

protocol HistoryDataStore {
    //var name: String { get set }
}


typealias HistoryInteraction = HistoryLogic & HistoryDataStore
class HistoryInteractor: HistoryInteraction {
    private let presenter: HistoryPresentationLogic!
    //var name: String = ""
    
    init(presenter: HistoryPresentationLogic) {
        self.presenter = presenter
    }
    
    func viewDidFinishLoading() {
    }
}
