//
//  HistoryPresenter.swift
//  Atlas
//
//  Created by Parvin Sital on 03/08/2020.
//  Copyright (c) 2020 Parvin Sital. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryPresentationLogic {
    func setup(viewController: HistoryDisplayLogic)
}

class HistoryPresenter {
    weak var viewController: HistoryDisplayLogic?
}

extension HistoryPresenter: HistoryPresentationLogic {
    func setup(viewController: HistoryDisplayLogic) {
        self.viewController = viewController
    }
}
