//
//  HistoryDI.swift
//  Atlas
//
//  Created by Parvin Sital on 03/08/2020.
//  Copyright (c) 2020 Parvin Sital. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import Swinject

class HistoryDI: ServiceInjection {
    func setDependencies(inContainer container: Container) {
        container.autoregister(HistoryInteraction.self, initializer: HistoryInteractor.init)
        container.autoregister(HistoryPresentationLogic.self, initializer: HistoryPresenter.init)
        container.autoregister(HistoryRouterProtocol.self, initializer: HistoryRouter.init)
        container.register(HistoryViewController.self) { r in
            HistoryViewController()
        }.initCompleted { r, vc in
            let interactor = r.resolve(HistoryInteraction.self)!
            let router = r.resolve(HistoryRouterProtocol.self)!
            let presenter = r.resolve(HistoryPresentationLogic.self)!
            
            vc.setup(interactor: interactor)
            vc.setup(router: router)

            
            router.setup(dataStore: interactor)
            router.setup(viewController: vc)
            
            presenter.setup(viewController: vc)
        }.initCompleted(resolveLocalization)
    }
}
