# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :tests do
    tests_passed = scan(scheme: "Atlas", fail_build: false)
    
    if not tests_passed
      derived_data_path = lane_context[SharedValues::SCAN_DERIVED_DATA_PATH]
      archive_xcresults(derived_data_path: derived_data_path)
      UI.user_error!("Tests failed")
    end
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :archive_xcresults do |options|
    test_logs_folder_path = "#{options[:derived_data_path]}/Logs/Test"

    if File.exist?(test_logs_folder_path)
        project_dir = File.expand_path("..", Dir.pwd)
        test_results_folder = "#{project_dir}/testresults"
        Dir.mkdir(test_results_folder)
        xcresults = Dir["#{test_logs_folder_path}/*.xcresult"]
        xcresults.each do |xcresult|
            puts "copying #{xcresult} to #{test_results_folder}"
            FileUtils.cp_r(xcresult, test_results_folder)
        end
    else
        puts "No test logs folder"
    end
  end

  lane :beta do
    ensure_git_status_clean
    ensure_git_branch
    sync_code_signing(type: "appstore") 
    build_app(scheme: "Atlas", workspace: "Atlas.xcworkspace", include_bitcode: true)
    increment_build_number
    increment_version_number(bump_type: "patch")
    upload_to_testflight(distribute_external: true, groups: "feedback-providers")
    reset_git_repo
  end
end