//
//  SavedEventsInteractor.swift
//  Atlas
//
//  Created by Parvin Sital on 27/07/2020.
//  Copyright (c) 2020 Parvin Sital. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SavedEventsBusinessLogic {
    func doSomething(request: SavedEvents.Something.Request)
}

protocol SavedEventsDataStore {
    //var name: String { get set }
}

typealias SavedEventsInteraction = SavedEventsDataStore & SavedEventsBusinessLogic

class SavedEventsInteractor: SavedEventsDataStore {
    var presenter: SavedEventsPresentationLogic?

    init(presenter: SavedEventsPresentationLogic) {
        self.presenter = presenter
    }
}

extension SavedEventsInteractor: SavedEventsBusinessLogic {
    func doSomething(request: SavedEvents.Something.Request) {
        
    }
}
