//
//  SavedEventsPresenter.swift
//  Atlas
//
//  Created by Parvin Sital on 27/07/2020.
//  Copyright (c) 2020 Parvin Sital. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SavedEventsPresentationLogic {
    func setup(viewController: SavedEventsDisplayLogic)
    func presentSomething(response: SavedEvents.Something.Response)
}

class SavedEventsPresenter {
    weak var viewController: SavedEventsDisplayLogic?
}

extension SavedEventsPresenter: SavedEventsPresentationLogic {
    func presentSomething(response: SavedEvents.Something.Response) {
        let viewModel = SavedEvents.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func setup(viewController: SavedEventsDisplayLogic) {
        self.viewController = viewController
    }
}
