//
//  SavedEventsRouter.swift
//  Atlas
//
//  Created by Parvin Sital on 27/07/2020.
//  Copyright (c) 2020 Parvin Sital. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SavedEventsRoutingLogic {
    func setup(viewController: SavedEventsViewController)
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol SavedEventsDataPassing {
    func setup(dataStore: SavedEventsDataStore)
    var dataStore: SavedEventsDataStore? { get }
}

typealias SavedEventsRoutingProtocol = NSObject
    & SavedEventsRoutingLogic
    & SavedEventsDataPassing

class SavedEventsRouter: SavedEventsRoutingProtocol {
    weak var viewController: SavedEventsViewController?
    var dataStore: SavedEventsDataStore?
    
    func setup(dataStore: SavedEventsDataStore) {
        self.dataStore = dataStore
    }
        
    func setup(viewController: SavedEventsViewController) {
        self.viewController = viewController
    }
    
    //func routeToSomewhere(segue: UIStoryboardSegue?) {
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: SavedEventsViewController, destination: SomewhereViewController) {
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: SavedEventsDataStore, destination: inout SomewhereDataStore) {
    //  destination.name = source.name
    //}
}
