//
//  SavedEventsViewController.swift
//  Atlas
//
//  Created by Parvin Sital on 27/07/2020.
//  Copyright (c) 2020 Parvin Sital. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SavedEventsDisplayLogic: class {
    func setup(interactor: SavedEventsInteraction)
    func setup(router: SavedEventsRoutingProtocol)
    func displaySomething(viewModel: SavedEvents.Something.ViewModel)
}

class SavedEventsViewController: UIViewController {
    var interactor: SavedEventsInteraction?
    var router: SavedEventsRoutingProtocol?
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
}
extension SavedEventsViewController: SavedEventsDisplayLogic {
    func doSomething() {
        let request = SavedEvents.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: SavedEvents.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
    
    func setup(interactor: SavedEventsInteraction) {
        self.interactor = interactor
    }
    
    func setup(router: SavedEventsRoutingProtocol) {
        self.router = router
    }
}

