//
//  BuyTicketRouter.swift
//  Atlas
//
//  Created by Parvin Sital on 04/08/2020.
//  Copyright (c) 2020 Parvin Sital. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol BuyTicketRouting {
    func setup(viewController: BuyTicketViewController)
}

protocol BuyTicketDataPassing {
    var dataStore: BuyTicketDataStore? { get }
    func setup(dataStore: BuyTicketDataStore)
}
typealias BuyTicketRouterProtocol = NSObject
    & BuyTicketRouting
    & BuyTicketDataPassing

class BuyTicketRouter: BuyTicketRouterProtocol {
    weak var viewController: BuyTicketViewController?
    var dataStore: BuyTicketDataStore?
    
    func setup(viewController: BuyTicketViewController) {
        self.viewController = viewController
    }
    
    func setup(dataStore: BuyTicketDataStore) {
        self.dataStore = dataStore
    }
}
