//
//  BuyTicketViewController.swift
//  Atlas
//
//  Created by Parvin Sital on 04/08/2020.
//  Copyright (c) 2020 Parvin Sital. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BuyTicketDisplayLogic: class {
    func setup(interactor: BuyTicketInteraction)
    func setup(router: BuyTicketRouterProtocol)
}

final class BuyTicketViewController: UIViewController {
    var interactor: BuyTicketInteraction?
    var router: BuyTicketRouterProtocol?
    private let wipLabel = UILabel(styling: .primary)
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupViews()
        interactor?.viewDidFinishLoading()
    }
}

private extension BuyTicketViewController {
    func setupViews() {
        view.backgroundColor = .systemBackground
        setupNavigation()
        setupWIPLabel()
    }
    
    
    func setupNavigation() {
        navigationItem.title = NSLocalizedString("tickets", comment: "")
    }
    
    func setupWIPLabel() {
        wipLabel.text = "WIP"
        view.addSubview(wipLabel)
        wipLabel.translatesAutoresizingMaskIntoConstraints = false
        
        let centerY = wipLabel.centerYAnchor.constraint(equalTo: view.centerYAnchor)
        let centerX = wipLabel.centerXAnchor.constraint(equalTo: view.centerXAnchor)
        NSLayoutConstraint.activate([centerY, centerX])
    }
}

extension BuyTicketViewController: BuyTicketDisplayLogic {
    func setup(interactor: BuyTicketInteraction) {
        self.interactor = interactor
    }
    func setup(router: BuyTicketRouterProtocol) {
        self.router = router
    }
}
