//
//  BuyTicketInteractor.swift
//  Atlas
//
//  Created by Parvin Sital on 04/08/2020.
//  Copyright (c) 2020 Parvin Sital. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BuyTicketLogic {
    func viewDidFinishLoading()
}

protocol BuyTicketDataStore {
    //var name: String { get set }
}


typealias BuyTicketInteraction = BuyTicketLogic & BuyTicketDataStore
class BuyTicketInteractor: BuyTicketInteraction {
    private let presenter: BuyTicketPresentationLogic!
    //var name: String = ""
    
    init(presenter: BuyTicketPresentationLogic) {
        self.presenter = presenter
    }
    
    func viewDidFinishLoading() {
    }
}
