//
//  BuyTicketDI.swift
//  Atlas
//
//  Created by Parvin Sital on 04/08/2020.
//  Copyright (c) 2020 Parvin Sital. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import Swinject

class BuyTicketDI {
    static func setDependencies(inContainer container: Container) {
        container.autoregister(BuyTicketInteraction.self, initializer: BuyTicketInteractor.init)
        container.autoregister(BuyTicketPresentationLogic.self, initializer: BuyTicketPresenter.init)
        container.autoregister(BuyTicketRouterProtocol.self, initializer: BuyTicketRouter.init)
        container.register(BuyTicketViewController.self) { r in
            BuyTicketViewController()
        }.initCompleted { r, vc in
            let interactor = r.resolve(BuyTicketInteraction.self)!
            let router = r.resolve(BuyTicketRouterProtocol.self)!
            let presenter = r.resolve(BuyTicketPresentationLogic.self)!
            
            vc.setup(interactor: interactor)
            vc.setup(router: router)

            
            router.setup(dataStore: interactor)
            router.setup(viewController: vc)
            
            presenter.setup(viewController: vc)
        }
    }
}
