//
//  BuyTicketPresenter.swift
//  Atlas
//
//  Created by Parvin Sital on 04/08/2020.
//  Copyright (c) 2020 Parvin Sital. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BuyTicketPresentationLogic {
    func setup(viewController: BuyTicketDisplayLogic)
}

class BuyTicketPresenter {
    weak var viewController: BuyTicketDisplayLogic?
}

extension BuyTicketPresenter: BuyTicketPresentationLogic {
    func setup(viewController: BuyTicketDisplayLogic) {
        self.viewController = viewController
    }
}
