name: Build

on:
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pod install --repo-update --verbose
    - name: Set up environment
      run: echo "$AWS_CONFIG" | base64 -o awsconfiguration.json
      env:
        AWS_CONFIG: ${{ secrets.AWS_CONFIG }}
    - name: Clean project
      run: xcodebuild -workspace Atlas.xcworkspace -scheme Atlas -sdk iphonesimulator clean
    - name: Build For Testing
      run: xcodebuild -workspace Atlas.xcworkspace -scheme Atlas -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.3' build-for-testing -quiet
