name: Build

on: [push]
  # pull_request:
    # branches: 
    # - develop
    # - master
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pod install --repo-update --verbose
    - name: Set up environment
      run: echo "$AWS_CONFIG" | base64 -o awsconfiguration.json
      env:
        AWS_CONFIG: ${{ secrets.AWS_CONFIG }}
    - name: Set Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_11.4.1.app
    - name: Run fastlane
      run: sudo bundle exec fastlane tests
    - name: Archive xcresults
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: testresults
        path: testresults
    # - name: Build For Testing
    #   run: xcodebuild build-for-testing -workspace Atlas.xcworkspace -scheme Atlas -destination "platform=iOS Simulator,name=iPhone 8,OS=13.4.1"
    # - name: Run Tests
    #   run: xcodebuild test-without-building -workspace Atlas.xcworkspace -scheme Atlas -destination "platform=iOS Simulator,name=iPhone 8,OS=13.4.1"