name: Swift

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: PrintDir
      run: pwd
    - name: CheckDir
      run: ls -a
